# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskTape AR Features' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskTape AR Features
	
  pod 'ARCL'
  
  pod 'Alamofire', '~> 4.6'

end
